# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gts7xl-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter gts7xl,$(TARGET_DEVICE)),)

endif
